version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7

  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    ignore:
      - dependency-name: "com.github.navikt.tbd-libs:*"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7

  # Oppdatering uten cooldown for tbd-libs
  - package-ecosystem: "gradle"
    allow:
      - dependency-name: "com.github.navikt.tbd-libs:*"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Oslo"
