version: 2

registries:
  maven-github:
    type: maven-repository
    url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
    username: POSTMAN
    password: PAT

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7

  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
      exclude:
        - "com.github.navikt.tbd-libs:*"
    registries:
      - maven-github
