apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: behovsakkumulator
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 25
  readiness:
    path: /isready
    initialDelay: 25
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-behovsakkumulator-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
