apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: behovsakkumulator
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  resources:
    limits:
      memory: 8192Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 4
    max: 4
    cpuThresholdPercentage: 500
  kafka:
    pool: nav-prod
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-behovsakkumulator-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
